
List<String> ipucuDondur(String ceviriYapilacakDil ) {
  return ipucum[ceviriYapilacakDil]!;
}



Map<String, List<String>> ipucum = {
  'tr': [
    'İngiliz kırmızı evde oturuyor. ',
    'İsveçlinin köpeği var.',
    'Danimarkalı çay içiyor.',
    'Yeşil ev tam siyah evin solunda duruyor.',
    'Yeşil evin sahibi kahve içmeyi seviyor.',
    'Palmall sigarası içenin bir kuşu var.',
    'Ortadaki evde oturan süt içmeyi seviyor.',
    'Sarı evde oturan Dunhill sigarası içiyor.',
    'Norveçli birinci evde oturuyor.',
    'Marlboro içen, kedisi olanın yanındaki evde oturuyor.',
    'Atı olan insan, Dunhill sigarası içenin yanındaki evde oturuyor.',
    'Winfield sigarası içen, birayı seviyor.',
    'Mavi evin yanında Norveçli oturuyor.',
    'Alman Price sigarası içiyor.',
    'Marlboro içenin komşusu su içiyor. ',
  ],
  'ing': [
    'The English lives in the red house',
    'The Swede has a dog',
    'The Danish is drinking tea',
    'The green house is just to the left of the black house.',
    'The owner of the green house likes to drink coffee',
    'He who smokes Palmall has a bird',
    'The resident in the middle house likes to drink milk.',
    'Sitting in the yellow house smokes Dunhill',
    'Norwegian lives in first house',
    'The one who smokes Marlboro lives in the house next to the one who has a cat',
    'The man with the horse lives in the house next to the Dunhill smoker',
    'Winfield smoker loves beer',
    'Norwegian lives next to the blue house',
    'German Price smokes',
    'The neighbor of the one who drinks Marlboro is drinking water. ',
  ],
  'alm': [
    "Der Engländer wohnt im roten Haus",
    'Der Schwede hat einen Hund',
    'Der Däne trinkt Tee',
    'Das grüne Haus ist direkt links vom schwarzen Haus.',
    'Der Besitzer des Gewächshauses trinkt gerne Kaffee',
    'Wer Palmall raucht, hat einen Vogel',
    'Der Bewohner des mittleren Hauses trinkt gerne Milch.',
    'Sitzen im gelben Haus raucht Dunhill',
    'Norweger wohnt im ersten Haus',
    'Derjenige, der Marlboro raucht, wohnt im Haus neben demjenigen, der eine Katze hat',
    "Der Mann mit dem Pferd wohnt im Haus neben dem Raucher von Dunhill",
    'Winfield-Raucher liebt Bier',
    'Norweger wohnt neben dem blauen Haus',
    'Deutscher Preis raucht',
    'Der Nachbar von dem, der Marlboro trinkt, trinkt Wasser. ',
  ],
  'frn': [
    "L'Anglais vit dans la maison rouge",
    "Le Suédois a un chien",
    'Le Danois boit du thé',
    'La maison verte est juste à gauche de la maison noire.',
    'Le propriétaire de la maison verte aime boire du café',
    'Celui qui fume du Palmall a un oiseau',
    'Le résident de la maison du milieu aime boire du lait.',
    'Assis dans la maison jaune fume Dunhill',
    "Le norvégien vit dans la première maison",
    'Celui qui fume de la Marlboro vit dans la maison à côté de celui qui a un chat',
    "L'homme au cheval vit dans la maison à côté du fumeur Dunhill",
    "Le fumeur de Winfield aime la bière",
    'Le Norvégien habite à côté de la maison bleue',
    'Le prix allemand fume',
    'Le voisin de celui qui boit de la Marlboro boit de l' 'eau. ',
  ],
  'cin': [
    '英国人住在红房子里',
    '瑞典人有一条狗',
    '丹麦人在喝茶',
    '绿色房子就在白色房子的左边。',
    '绿屋主人喜欢喝咖啡',
    'Pall Mall 吸烟者有一只鸟',
    '中屋的住户喜欢喝牛奶。',
    '坐在黄色的房子里抽登喜路',
    '挪威人住在第一所房子',
    '抽万宝路的人住在养猫人的隔壁房子里',
    '骑马的人住在登喜路吸烟者旁边的房子里',
    '温菲尔德吸烟者喜欢啤酒',
    '挪威人住在蓝房子旁边',
    '德国价格抽烟',
    '喝万宝路的人的邻居正在喝水。 ',
  ],
  'isp':[
    'El inglés vive en la casa roja',
    'El sueco tiene un perro',
    'El danés está bebiendo té',
    'La casa verde está justo a la izquierda de la casa negra.',
    'Al dueño de la casa verde le gusta tomar café',
    'El que fuma Palmall tiene pájaro',
    'Al residente de la casa del medio le gusta beber leche.',
    'Sentado en la casa amarilla fuma Dunhill',
    'Noruego vive en primera casa',
    'El que fuma Marlboro vive en la casa de al lado del que tiene gato',
    'El hombre con el caballo vive en la casa al lado del fumador Dunhill',
    'El fumador de Winfield ama la cerveza',
    'Noruego vive al lado de la casa azul',
    'El precio alemán fuma',
    'El vecino del que bebe Marlboro está bebiendo agua. ',
  ],
  'ru':[
    'Англичанин живет в красном доме',
    'У шведа есть собака',
    'Датчанин пьет чай',
    'Зеленый дом находится слева от черного дома.',
    'Хозяин зелени любит пить кофе',
    'У того, кто курит Palmall, есть птица',
    'Житель среднего дома любит пить молоко.',
    'Сижу в желтом доме, курю Данхилл',
    'Норвежец живет в первом доме',
    'Тот, кто курит Marlboro, живет в доме рядом с тем, у кого есть кошка',
    'Человек с лошадью живет в доме рядом с курильщиком Данхилла',
    'Курильщик Winfield любит пиво',
    'Норвежец живет рядом с голубым домом',
    'Немец Прайс курит',
    'Сосед того, кто пьет Мальборо, пьет воду. ',
  ],
  'it':[
    'L inglese vive nella casa rossa',
    'Lo svedese ha un cane',
    "Il danese sta bevendo il tè",
    'La casa verde è appena a sinistra della casa nera.',
    "Al proprietario della casa verde piace bere il caffè",
    'Chi fuma Palmall ha un uccello',
    'Al residente nella casa di mezzo piace bere il latte.',
    'Seduto nella casa gialla fuma Dunhill',
    'Il norvegese vive nella prima casa',
    'Quello che fuma Marlboro vive nella casa accanto a quello che ha un gatto',
    "L'uomo con il cavallo vive nella casa accanto al fumatore di Dunhill",
    'Il fumatore di Winfield ama la birra',
    'Il norvegese vive accanto alla casa blu',
    'Il prezzo tedesco fuma',
    'Il vicino di chi beve Marlboro sta bevendo acqua. ',
  ],
  'ja':[
    '「英国人は赤い家に住んでいる」',
    '「スウェーデン人は犬を飼っている」',
    '「デンマーク人はお茶を飲んでいます」',
    'グリーン ハウスはホワイト ハウスのすぐ左側にあります。',
    '「温室のオーナーはコーヒーを飲むのが好きです」',
    '「パルモールを吸う者は鳥を飼っている」',
    '「真ん中の家の住人は牛乳を飲むのが好きです。」',
    '「黄色い家に座ってダンヒルを吸う」',
    '「ノルウェー人は最初の家に住んでいます」',
    '「マールボロを吸う人は、猫を飼っている人の隣の家に住んでいる」',
    '「馬を持った男はダンヒル喫煙者の隣の家に住んでいる」',
    '「ウィンフィールドの喫煙者はビールが大好き」',
    '「ノルウェー人は青い家の隣に住んでいます」',
    '「ドイツの価格は煙る」',
    '「マールボロを飲む人の隣人は飲料水です。 ',
  ],
  'isv':[
    'Engelsmannen bor i det röda huset',
    'Svensken har en hund',
    'Danskan dricker te',
    'Det gröna huset ligger precis till vänster om det svarta huset.',
    "Ägaren till det gröna huset gillar att dricka kaffe",
    "Den som röker Palmall har en fågel",
    'Boenden i mellanhuset gillar att dricka mjölk.',
    "Att sitta i det gula huset röker Dunhill",
    'Norrmannen bor i första huset',
    "Den som röker Marlboro bor i huset bredvid den som har en katt",
    "Mannen med hästen bor i huset bredvid Dunhill-rökaren",
    "Winfield rökare älskar öl",
    'Norrmannen bor bredvid det blå huset',
    "Tyska priset röker",
    'Grannen till den som dricker Marlboro dricker vatten. ',
  ],
  
};
